SANIT_FLAGS = -fsanitize=address,alignment,undefined
DEBUG = -D DUMP


all: MYBACK

MYBACK: main.o tree.o name_table.o read.o list.o
	@g++ -g $(DEBUG) $(SANIT_FLAGS) -o back.exe obj/main.o ../Tree/tree.o ../NameTable/name_table.o ../ReadingFile/read.o ../List/list.o

main.o: src/main.cpp
	@g++ -g $(DEBUG) $(SANIT_FLAGS) -c src/main.cpp -o obj/main.o

tree.o: ../Tree/tree.cpp
	@g++ -g $(DEBUG) $(SANIT_FLAGS) -c ../Tree/tree.cpp -o ../Tree/tree.o

name_table.o: ../NameTable/name_table.cpp
	@g++ -g $(SANIT_FLAGS) -c ../NameTable/name_table.cpp -o ../NameTable/name_table.o

read.o:	../ReadingFile/read.cpp
	@g++ -g $(SANIT_FLAGS) -c ../ReadingFile/read.cpp -o ../ReadingFile/read.o

list.o: ../List/list.cpp
	@g++ -g $(DEBUG) $(SANIT_FLAGS) -c ../List/list.cpp -o ../List/list.o

clean:
	rm obj/* back.exe ../Tree/*.o ../NameTable/*.o ../ReadingFile/*.o ../List/*.o