SANIT_FLAGS = -fsanitize=address,alignment,undefined
DEBUG = -D DUMP


all: MYBACK

MYBACK: main.o tree.o name_table.o read.o list.o
	@g++ -g $(DEBUG) $(SANIT_FLAGS) -o back.exe obj/main.o inc/Tree_backend/tree.o inc/NameTable_backend/name_table.o inc/ReadingFile_backend/read.o inc/List_backend/list.o

main.o: src/main.cpp
	@g++ -g $(DEBUG) $(SANIT_FLAGS) -c src/main.cpp -o obj/main.o

tree.o: inc/Tree_backend/tree.cpp
	@g++ -g $(DEBUG) $(SANIT_FLAGS) -c inc/Tree_backend/tree.cpp -o inc/Tree_backend/tree.o

name_table.o: inc/NameTable_backend/name_table.cpp
	@g++ -g $(SANIT_FLAGS) -c inc/NameTable_backend/name_table.cpp -o inc/NameTable_backend/name_table.o

read.o:	inc/ReadingFile_backend/read.cpp
	@g++ -g $(SANIT_FLAGS) -c inc/ReadingFile_backend/read.cpp -o inc/ReadingFile_backend/read.o

list.o: inc/List_backend/list.cpp
	@g++ -g $(DEBUG) $(SANIT_FLAGS) -c inc/List_backend/list.cpp -o inc/List_backend/list.o

clean:
	rm obj/* back.exe inc/Tree_backend/*.o inc/NameTable_backend/*.o inc/ReadingFile_backend/*.o inc/List_backend/*.o